### ISSUE TITLE
"Use Large Smoke Explosion" does not affect manually detonated Stickybombs

### ISSUE THREAD

**Issue by SoulBlast35** [nosoop/SM-TFAttributeSupport#10]
Never noticed this before because Ive only done this on Robot Demomen, who never manually detonate, but the giant smoke blast only occurs if the Stickybomb(s) detonate if they are forced to from going over the set limit for the Launcher being used. Quite low priority, but just something I thought I'd note.

**Comment by nosoop** [comment]
Yeah, that's a really weird case.  They both run the same code path and should be able to use the large smoke explosions, but for some reason the `DispatchParticleEffect` only renders on one and not the other.

I have a fix for this all ready to go, but DHooks just isn't playing nice as usual.

Feel free to compile the referenced commit below if you'd like to try it out.  It's known to conflict with having the Starter Pack loaded in.

**Comment by SoulBlast35** [comment]
Doesnt seem to be working for me, Server hard-crashes upon detonating a smokebomb sticky. Its not high priority though and I kinda like using the Starter Pack a lot. Speaking of that, found an oddity with it that I submitted an issue for

**Comment by nosoop** [comment]
Yeah, the hard crashing is the DHooks not playing nice as usual.  Plugin-based virtual hooks are an absolute mess.
