### ISSUE TITLE
`Set DamageType Ignite` is failing to re-apply ignition.

### ISSUE THREAD

**Issue by PonyPhreak** [nosoop/SM-TFAttributeSupport#12]
`Set DamageType Ignite` is failing to re-apply ignition.

For example, if I use  "Set DamageType Ignite" "5" on an item the first hit applies 5 seconds of afterburn.  If I hit the same target after 3 second pass it should reset afterburn back to 5 seconds, but it doesn't. Instead the target burns for 2 more seconds, then the afterburn expires.   No matter the value or weapon type, (shotgun, melee, minigun, grenade launcher, etc) it always seems to view the value as static. Initial hits on non-ignited targets will apply the afterburn, subsequent hits will not re-apply/refresh/extend its timer.

**Comment by nosoop** [comment]
That's definitely a bug for ~~our desired use case~~ my intended result, but it looks like the intended behavior for the new afterburn system.

The other afterburn-related function in the game (`CTFWeaponBase::GetAfterburnRateOnHit()`) adds on top of the existing duration, so in your particular scenario the target would burn for 10 seconds in total.

Will probably have a fix tested later today.
