### ISSUE TITLE
Bug: `"Set DamageType Ignite"` applies afterburn to pyros for full duration.

### ISSUE THREAD

**Issue by PonyPhreak** [nosoop/SM-TFAttributeSupport#22]
`"Set DamageType Ignite"` will cause pyros to visibly burn, for the full duration, and will allow "vs burning" effects to proc (eg `minicrit vs burning player`, `damage bonus vs burning`).  the afterburn itself deals no damage.

https://github.com/nosoop/SM-TFAttributeSupport/assets/35093438/604ceb2c-ad34-442d-bd9f-c6d83d200074

This demonstration uses a CWX Shotgun that has 2 important attributes on it

` "Set DamageType Ignite"       "5"`
`"damage bonus vs burning"	"1.75"`

The second shot hitting for ~90, instead of ~50, shows the bonus damage is being applied due to burning- As does the Axtinguisher's minicrit.

**Comment by nosoop** [comment]
Attached is a build based on [the ignite-fix-test branch](https://github.com/nosoop/SM-TFAttributeSupport/tree/ignite-fix-test); please test it for regressions in behavior and let me know if it resolves the issue.

[ignite-fix-test.zip](https://github.com/nosoop/SM-TFAttributeSupport/files/12780299/ignite-fix-test.zip)

**Comment by PonyPhreak** [comment]
So far, so good. everything appears to be working perfectly fine.
