### ISSUE TITLE
Bug: Concheror buff not applying lifesteal aura.

### ISSUE THREAD

**Issue by PonyPhreak** [nosoop/SM-TFAttributeSupport#30]
On buff activation, I still receive the speed boost, but do not regain hp when dealing damage.

https://github.com/user-attachments/assets/dd7b99bf-1b8b-4587-baab-b355529c3e4c

`Note: I've disabled any weapon modifications in this clip -- that is a valve standard conch`

**Comment by nosoop** [comment]
Probably an issue in `healing_source_modifiers.sp` (internal plugin), since that's supposed to control the changed healing source behaviors.

**Comment by nosoop** [comment]
Yeah; closing this since this appears to be a bug in a different plugin.
