### ISSUE TITLE
Bug: `upgrade rate decrease` not applying upgrade mult

### ISSUE THREAD

**Issue by PonyPhreak** [nosoop/SM-TFAttributeSupport#31]
`upgrade rate decrease` is no longer applying any changes to upgrade values.
The clip below should be showing 50 metal per swing.

https://github.com/user-attachments/assets/1b48b92a-4723-4d52-b066-45a4e5bcb956

**Comment by nosoop** [comment]
This is working as expected on an unmodified server.
