### ISSUE TITLE
Touching resupply closet closes windows srcds server when using other plugins that modifies attributes.

### ISSUE THREAD

**Issue by higps** [nosoop/SM-TFAttributeSupport#6]
I'm using JugadorXei's plugin to alter attributes, as it adds the feature of having displayable documentation in game.

If this plugin is loaded and anyone touches a resupply closet, it just closes the server.

If I only run tf2attributes from your fork and this one, whenever someone touches a resupply closet this error is thrown

08/13/2021 - 20:33:45: [SM] Exception reported: NULL not allowed
L 08/13/2021 - 20:33:45: [SM] Blaming: tf2attribute_support.smx
L 08/13/2021 - 20:33:45: [SM] Call stack trace:
L 08/13/2021 - 20:33:45: [SM]   [0] GetPlayerWeaponSlot
L 08/13/2021 - 20:33:45: [SM]   [1] Line 243, D:\tf2server\tf2\tf\addons\sourcemod\scripting\tf2attribute_support.sp::OnPlayerRegeneratePost

**Comment by nosoop** [comment]
Interesting, thanks for the report.

Is DHooks also up to date?  I suspect that it could be peace-maker/DHooks2#2 all over again, detours on Windows are notoriously finicky.

I rechecked the signature for this and it should be current for the game.  Unfortunately the drive with my Windows dedicated server stuff is dozing off at the moment, but feel free to compile and test [the `resup-detour-kludge` branch](https://github.com/nosoop/SM-TFAttributeSupport/tree/resup-detour-kludge) and let me know if that resolves the issue (provided you are also on the latest version of DHooks).

If you're unable to compile / test, I should be able to myself within the next day.

**Comment by nosoop** [comment]
I'm unable to reproduce this issue on Windows using the latest commit from `master` (i.e. without the pre-hook fix provided by `resup-detour-kludge`) and DHooks version 2.2.0-detours17.  I've also tested it against the latest revision of [Rebalance Fortress 2](https://github.com/JugadorXEI/tf2rebalance_jug) without any crashes or unexpected side effects.

That version of DHooks seems stable in my experience, so I don't see any reason to stay on older releases; I think I was running detours14 for a while for that reason.  Let me know if you've updated DHooks and are / are not able to reproduce the issue, or if the extension has a specific known issue preventing you from doing so.

**Comment by higps** [comment]
Updating Dhooks solved it
