### ISSUE TITLE
[Bug] Unable to select Gas Passer after dying with it at 100% charge

### ISSUE THREAD

**Issue by higps** [nosoop/SM-TFAttributeSupport#7]
If you die with the gas passer and it has 100% charge, you won't be able to select it, unless you run in to a resupply locker.

On spawn it's as if you don't have a secondary weapon.

Steps to reproduce:
1. Equip Gas Passer
2. Build charge by doing damage
3. Die at full charge
4. Respawn and you are unable to select the secondary weapon slot

**Comment by nosoop** [comment]
Thanks for the report!  I've verified this and will have a fix released shortly.
