### ISSUE TITLE
Override projectile type with Pipebomb  value deals no damage

### ISSUE THREAD

**Issue by higps** [nosoop/SM-TFAttributeSupport#9]
Using the Attribute ID 280 with the value 3 on a shotgun makes the enemy take no damage, and the user only take 5 self damage if standing too close.

Rockets, flare, arrows works, just not pipes.

**Comment by nosoop** [comment]
Grenades are one of the things in the TF2 code that I'd actually consider spaghetti code.

Latest release should have a fix for this; thank you for the report.

**Comment by nosoop** [comment]
Have to roll this version of the fix back as it seems to causes inconsistent crashes on Linux.  Will reopen for the time being.

https://crash.limetech.org/pvl7ou3nafaz

Might be better to hook something on `FireProjectile`.

**Comment by higps** [comment]
This issue still remains in the current version as well
